#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#include <cstdint>
#include <cstdlib>
#include <pthread.h>
#include <time.h>
#include <sys/types.h>
#include <unordered_set>
#include <unordered_map>
#include <chrono>
#include <string>
#include <vector>

/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libanogs.so'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long
#define _BYTE unsigned char
#define _WORD unsigned short
#define _DWORD unsigned int
#define _QWORD unsigned long long
#define _OWORD __int128

struct $02D3975949B56402107C534E336AFF12;
struct sockaddr;

#define LOG_COLOR_RED    "🔴🔴🔴 "
#define LOG_COLOR_RESET  " ⚪⚪⚪"

namespace MyNamespace {
    /* 1 */
    struct MyElf64_Sym
    {
        unsigned __int32 st_name;
        unsigned __int8 st_info;
        unsigned __int8 st_other;
        unsigned __int16 st_shndx;
        unsigned __int64 st_value;
        unsigned __int64 st_size;
    };

    /* 2 */
    struct MyElf64_Rela
    {
        unsigned __int64 r_offset;
        unsigned __int64 r_info;
        __int64 r_addend;
    };

    /* 3 */
    struct MyElf64_Dyn
    {
        unsigned __int64 d_tag;
        unsigned __int64 d_un;
    };

    /* 4 */
    struct MyElf64_Verdef
    {
        unsigned __int16 vd_version;
        unsigned __int16 vd_flags;
        unsigned __int16 vd_ndx;
        unsigned __int16 vd_cnt;
        unsigned __int32 vd_hash;
        unsigned __int32 vd_aux;
        unsigned __int32 vd_next;
    };

    /* 5 */
    struct MyElf64_Verdaux
    {
        unsigned __int32 vda_name;
        unsigned __int32 vda_next;
    };

    /* 6 */
    struct MyElf64_Verneed
    {
        unsigned __int16 vn_version;
        unsigned __int16 vn_cnt;
        unsigned __int32 vn_file;
        unsigned __int32 vn_aux;
        unsigned __int32 vn_next;
    };

    /* 7 */
    struct MyElf64_Vernaux
    {
        unsigned __int32 vna_hash;
        unsigned __int16 vna_flags;
        unsigned __int16 vna_other;
        unsigned __int32 vna_name;
        unsigned __int32 vna_next;
    };
}

typedef unsigned int uint32_t;
typedef unsigned short uint16_t;
typedef unsigned char uint8_t;

struct ARM64Registers {
    uint64_t x[31];
    uint64_t sp;
    uint64_t pc;
    uint64_t cpsr;
};

static void save_registers(ARM64Registers* regs) {
    asm volatile (
            "stp x0, x1, [%[regs]]\n\t"
            "stp x2, x3, [%[regs], #16]\n\t"
            "stp x4, x5, [%[regs], #32]\n\t"
            "stp x6, x7, [%[regs], #48]\n\t"
            "stp x8, x9, [%[regs], #64]\n\t"
            "stp x10, x11, [%[regs], #80]\n\t"
            "stp x12, x13, [%[regs], #96]\n\t"
            "stp x14, x15, [%[regs], #112]\n\t"
            "stp x16, x17, [%[regs], #128]\n\t"
            "stp x18, x19, [%[regs], #144]\n\t"
            "stp x20, x21, [%[regs], #160]\n\t"
            "stp x22, x23, [%[regs], #176]\n\t"
            "stp x24, x25, [%[regs], #192]\n\t"
            "stp x26, x27, [%[regs], #208]\n\t"
            "stp x28, x29, [%[regs], #224]\n\t"
            "mov %[sp], sp\n\t"
            "mov %[pc], lr\n\t"
            : [regs] "+r" (regs), [sp] "=r" (regs->sp), [pc] "=r" (regs->pc)
    );
}

struct CallInfo {
    int count;
    std::chrono::steady_clock::time_point last_reset;

    CallInfo() : count(0), last_reset(std::chrono::steady_clock::now()) {}
};

namespace GlobalDefs {
    const int SUSPICIOUS_CALL_THRESHOLD = 100;
    const int TIME_WINDOW_SECONDS = 60;

    using BlockedOffsets = std::unordered_set<uintptr_t>;
    using BlockedStrings = std::unordered_set<std::string>;
    using ObservedFunctions = std::unordered_set<void*>;
    using FoundStrings = std::unordered_set<std::string>;
    using CallInfoMap = std::unordered_map<uintptr_t, CallInfo>;

    inline bool isValidString(const void* ptr) {
        if (!ptr || (reinterpret_cast<uintptr_t>(ptr) < 0x10000)) return false;
        try {
            const char* str = static_cast<const char*>(ptr);
            return str[0] != '\0' && isprint(str[0]);
        } catch (...) {
            return false;
        }
    }

    inline bool isValidPointer(void* ptr) {
        return ptr && reinterpret_cast<uintptr_t>(ptr) > 0x10000;
    }

    inline bool isBlockedString(const char* str, const char* blocked_strings[], size_t num_strings) {
        if (!str) return false;

        for (size_t i = 0; i < num_strings; ++i) {
            if (strstr(str, blocked_strings[i]) != nullptr) {
                return true;
            }
        }
        return false;
    }
}

namespace Tools {
    uintptr_t GetBaseAddress(const char* library_name);

    bool Hook(const char* library_name, const char* symbol_name, void* hook_func, void** orig_func);
    bool HookSymbol(const char* library_name, const char* symbol_name, void* hook_func, void** orig_func);

    bool Patch(const char* library_name, const char* offset, const char* bytes);

    void read_proc_maps(const char* library_name);

    void RemapLibrary(const char* library_name);
}

extern uintptr_t base_address;

struct MonitoringInfo {
    uintptr_t offset;
    std::string caller_function;
    std::string string_param;
    uint64_t timestamp;
    bool was_blocked;
};

static std::vector<MonitoringInfo> monitoring_history;
static const size_t MAX_HISTORY = 100;

// extern void* off_CC78E88;
// extern void* off_CAAF590;
// extern void* off_CCA7C78;
// extern void* off_CBA42E8;
// extern void* off_CC69870;
// extern void* off_CD1AE90;

// void* off_CC78E88 = nullptr;
// void* off_CAAF590 = nullptr;
// void* off_CCA7C78 = nullptr;
// void* off_CBA42E8 = nullptr;
// void* off_CC69870 = nullptr;
// void* off_CD1AE90 = nullptr;

#endif // DEFINITIONS_H